# API server listen address
# Defauls to: ":8080" which will listen on all avalable interfaces.
listen: :8080

# Database configuration
# MongoDB is required to run the service
# Format: [mongodb://][user:pass@]host1[:port1][,host2[:port2],...][?options]
# Format doc: https://docs.mongodb.com/manual/reference/connection-string/
# Defaults to: "mongo-inventory"
mongo: mongo-inventory:27017

# Enable SSL for mongo connections
# Defaults to: false
# mongo_ssl: false

# SkipVerify controls whether a mongo client verifies the
# server's certificate chain and host name.
# If InsecureSkipVerify is true, accepts any certificate
# presented by the server and any host name in that certificate.
# Defaults to: false
# mongo_ssl_skipverify: false

# Mongodb username
# Overwrites username set in connection string.
# Defaults to: none
# mongo_username: user

# Mongodb password
# Overwrites password set in connection string.
# Defaults to: none
# mongo_password: secret

# HTTP Server middleware environment
# Available values:
#   dev
#       development environment
#   prod
#       production environment
# Defaults to: prod
# middleware: dev

# Maximum number of inventory attributes per device
# Defaults to: 100
# Overwrite with environment variable: INVENTORY_LIMIT_ATTRIBUTES
# limit_attributes: 100

# Maximum number of tags per device
# Defaults to: 20
# Overwrite with environment variable: INVENTORY_LIMIT_TAGS
# limit_tags: 20

# Mender-reporting enable switch
# Defaults to: false
# Overwrite with environment variable: INVENTORY_ENABLE_REPORTING
# enable_reporting: true

# Workflows service address
# Defaults to: http://mender-workflows-server:8080
# Overwrite with environment variable: INVENTORY_ORCHESTRATOR_ADDR
# orchestrator_addr: http://mender-workflows-server:8080
